import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { CustomTrigger } from "@/components/ui/CustomTrigger";
import { ViewportHeightProvider } from "@/components/ui/ViewportHeightProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "vjezba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#f8fafc] to-[#e0e7ef] min-h-[100dvh]`}
      >
        <ViewportHeightProvider />
        <SidebarProvider>
          <AppSidebar />
          <main className="mx-auto w-full max-w-4xl px-2 sm:px-6 py-6 pb-0 rounded-2xl shadow-xl bg-white/80 min-h-[80dvh] max-h-[90dvh] mt-6 overflow-y-hidden">
            <CustomTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
